### ISSUE TITLE
Invalid RMC data is parsed anyway

### ISSUE THREAD

**Issue by rob42** [SignalK/nmea0183-signalk#140]
When I run my GPS inside I get various bad RMC sentences (expected as the GPS has marginal coverage). Typical sentence has 0 for latitude and longitude, cog, etc

When the parser parses these sentences my vessel warp-drives off to Lat 0.0, Lon 0.0, just off ghana in africa :-(

Then it warps back a bit later...  The vessel track shows the 'excursion' too :-(

The parser should check for 'A' or 'V' and discard bad data:
```
 -      RMC          Recommended Minimum sentence C
[0]     123519       Fix taken at 12:35:19 UTC
[1]     A            Status A=active or V=Void.
[2][3]  4807.038,N   Latitude 48 deg 07.038' N
...
```
It should always assume the message is void if  0.0 is in Lat and Lon. This will work for everywhere on earth but one place few of us will ever go :-)

**Comment by davidsanner** [comment]
Having this same issue.

If RMC is missing fields I would think those values should not be set to 0.0 and either set to null or not set.

eg. navigation.variation should not be set to 0.0 if RMC sentence is missing either of the two required values.
I'm having the issue w/ downstream apps/plugins displaying magnetic / true north incorrectly.

I could do a PR if that would help

**Comment by davidsanner** [comment]
This PR #216 should process only well formed / valid values for lat/long/cog/sog/variation
