### ISSUE TITLE
VDM Meassage 21 AtoN request; Off position and Virtual.

### ISSUE THREAD

**Issue by Hakansv** [SignalK/nmea0183-signalk#166]
From VDM message 21 AtoN the "off-position indicator" and "Virtual AtoN flag" are missing.
It's sufficient to flag for either "off position" or "virtual". Absence of either of are understood as "on position" or "Real" respectively. 

Reference: [Message 21 example](https://www.navcen.uscg.gov/?pageName=AISMessage21)
![bild](https://user-images.githubusercontent.com/7202854/75097402-b3595980-55aa-11ea-9ce5-be56e366a589.png)
![bild](https://user-images.githubusercontent.com/7202854/75097387-8a38c900-55aa-11ea-9718-5da24a5ad624.png)
![bild](https://user-images.githubusercontent.com/7202854/75097395-a2104d00-55aa-11ea-82cb-dc5c66231eb5.png)

OCPN method to parse VDM message 21:
```
int offpos = bstr->GetInt( 260, 1 ); // off position flag
int virt = bstr->GetInt( 270, 1 ); // virtual flag
```

**Comment by sbender9** [comment]
I've added off position indicator: #168 

But the decoder we use does not support the virtual flag it would need to be added there first:

https://github.com/fulup-bzh/GeoGate/tree/master/encoder

**Comment by Hakansv** [comment]
@sbender9 
The "off position" flag is very good and appreciated. Thanks.

The virtual flag is possible to, although uncertain, detect from the mmsi number. (xxyyy6zzz) The "6" here is a recommended to use for a Virtual AtoN. But since it's a recommendation to use for states involved it can't be all time verified. A secure flag would be the one from the AtoN itself.
If it's possible to request that support from your decoder team we would be more safe even with data flowing though SK? 

There are so far two possible type of AtoN supported in message 21. "Real, "Virtual" ->270, 0/1. 
(There is a (future?) third type "Mobile" mentioned but to support that in message 21 it has to be redefined I think.)

**Comment by afischerdev** [comment]
I'll add the virtual flag in the encoder lib.
Do you have a test sentence with a positive flag?

**Comment by Hakansv** [comment]
@afischerdev 
Not so I exactly know where to find it for the moment. But I'll find, just give me a day or two and I be back.
Thanks
Håkan

**Comment by afischerdev** [comment]
@Hakansv 
Thanks, but not requiered anymore, I found one in the current test data.

**Comment by Hakansv** [comment]
![bild](https://user-images.githubusercontent.com/7202854/75142706-f1ae6000-56f3-11ea-93b2-5963b6a634a5.png)

**Comment by afischerdev** [comment]
I've updated the ggencoder package to version 1.0.4 and published at npm

**Comment by rgleason** [comment]
[AIS_aton-beacon-safewater-rotterdam-scheveningen.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4245848/AIS_aton-beacon-safewater-rotterdam-scheveningen.txt)
[AIS_dsc_mob-distress-simple-gibraltar.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4245849/AIS_dsc_mob-distress-simple-gibraltar.txt)
[AIS_dsc-mob-distress-simple-tokyo.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4245850/AIS_dsc-mob-distress-simple-tokyo.txt)
[AIS_aton-53-45n-09-25E.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4245851/AIS_aton-53-45n-09-25E.txt)

**Comment by Hakansv** [comment]
@afischerdev 
Many thanks! Really appreciated!
I'll make a test and revert.
Håkan

**Comment by Hakansv** [comment]
Hmm. Many contributors in this generous community! I was a bit eager, as usual?
The changes to GeoGate looks really promising.
So next step would be to incorporate the new flags in SignalK as well. Then I can test. 👍 
Thanks
Håkan

**Comment by sbender9** [comment]
Thanks @afischerdev !

Can you take a look at #165 also?

**Comment by sbender9** [comment]
I've also added these to the NMEA2000 parser: https://github.com/SignalK/n2k-signalk/pull/170

**Comment by sbender9** [comment]
Anyone have any sample data with a virtual aton?

**Comment by sbender9** [comment]
Anyone have any sample data with a virtual aton?

**Comment by Hakansv** [comment]
Here's a file with some AtoNs
(Thanks to Dirk)
[Dirk_rott_Aton.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4262382/Dirk_rott_Aton.txt)

**Comment by Hakansv** [comment]
And here I've "cleaned" it. 
One Virtual and one Real
[AtoN_Virt_Real.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4262724/AtoN_Virt_Real.txt)

**Comment by tkurki** [comment]
Afai can tell this was fixed.
