### ISSUE TITLE
BWC not recognized

### ISSUE THREAD

**Issue by dharvey** [SignalK/nmea0183-signalk#209]
My Seatalk 1 to NMEA 0183 converter does not put the lat/long position of a waypoint into the BWC sentence. As a result, the sentence is ignored by SignalK. I therefore cannot get other useful information out of BWC, in particular bearing to waypoint and distance to waypoint. Is there a way to make SignalK accept this sentence even though it is missing the lat/long data?

**Comment by joabakk** [comment]
These lines are what is causing this behaviour: https://github.com/SignalK/nmea0183-signalk/blob/master/hooks/BWC.js#L40-L42

It could be discussed if that check is really necessary

**Comment by tkurki** [comment]
Fix published as @signalk/nmea0183-signalk@3.10.3
