### ISSUE TITLE
HDG sentence incorrectly parsed

### ISSUE THREAD

**Issue by tvr256** [SignalK/nmea0183-signalk#235]
As mentioned in https://github.com/SignalK/specification/issues/242#issuecomment-1345666329 , the HDG sentence is incorrectly parsed:

If I send the following sentence `$INHDG,180,5,W,10,W*6D`

navigation.magneticDeviation is not set (should be -5)
navigation.magneticVariation is set to -10 (correct)
navigation.headingCompass is not set (should be 180)
navigation.headingMagnetic is set to 180 (should be 175)
navigation.headingTrue is not set (should be 165)

Incidentally, the [NMEA spec](https://www.plaisance-pratique.com/IMG/pdf/NMEA0183-2.pdf) clearly states that the first value in the HDG sentence is the magnetic sensor reading **before** any deviation correction is applied, and **not** the magnetic heading.

**Comment by tkurki** [comment]
Thanks for the heads up. Please check out the linked PR for the fix.
