### ISSUE TITLE
RMB parser stores next waypoint position to incorrect SignalK field

### ISSUE THREAD

**Issue by tvr256** [SignalK/nmea0183-signalk#240]
The RMB parser currently stores the next waypoint position to `navigation.courseRhumbline.nextPoint`

This is incorrect, it should be stored to `navigation.courseRhumbline.nextPoint.position`

**Comment by Techstyleuk** [comment]
Pull request submitted #252

https://github.com/SignalK/nmea0183-signalk/pull/252
